name: Forklift Build and Unit Test

on:
  push:
    branches: [feature/forklift]
  pull_request:
    branches: [feature/forklift]
    types: [opened]

jobs:
  build-and-unittest:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: ros_ws/src/ros2_ign_p2p_controllers

      - name: Install ROS 2 Humble and Dependencies
        run: |
          sudo apt update
          sudo apt install -y software-properties-common curl lcov python3-rosdep
          sudo add-apt-repository universe
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          sudo apt update
          sudo apt install -y ros-humble-ros-base python3-colcon-common-extensions

      - name: Initialize rosdep
        run: |
          sudo rosdep init || echo "rosdep already initialized"
          rosdep update --include-eol-distros

      - name: Set up ROS 2 workspace
        run: |
          source /opt/ros/humble/setup.bash
          mkdir -p ros_ws
          cd ros_ws
          colcon build
          source install/setup.bash

      - name: Install package dependencies
        run: |
          source /opt/ros/humble/setup.bash
          cd ros_ws
          rosdep install --from-paths src -y --ignore-src

      - name: Build and run unit tests
        run: |
          source /opt/ros/humble/setup.bash
          cd ros_ws
          colcon build --packages-select ros2_ign_p2p_controllers
          colcon test --packages-select ros2_ign_p2p_controllers
          colcon test-result --all --verbose
